import fs from 'fs';
import path from 'path';
import { AssessmentResult } from './orchestrator.js';

export class ReportGenerator {
  constructor(private result: AssessmentResult) {}

  generateMarkdown(): string {
    const { metrics, storeUrl, wcVersion, timestamp } = this.result;
    const scale = metrics.scale;
    const complexity = metrics.complexity;

    return `
# WooCommerce Migration Assessment Report
**Store URL:** ${storeUrl}
**WC Version:** ${wcVersion}
**Date:** ${new Date(timestamp).toLocaleString()}

## 1. Store Scale Metrics
| Entity | Count |
| --- | --- |
| Products | ${scale.productCount} |
| Variations | ${scale.variationCount} |
| Orders | ${scale.orderCount} |
| Customers | ${scale.customerCount} |
| Categories | ${scale.categoryCount} |

## 2. Technical Complexity Analysis
**Complexity Score:** ${complexity.score}/100
**Readiness Category:** ${complexity.readinessCategory}

### Product Type Distribution
${Object.entries(complexity.productTypeDistribution)
  .map(([type, count]) => `- **${type}:** ${count}`)
  .join('\n')}

## 3. Custom Logic Analysis
**Logic Density:** ${metrics.logic.logicDensity}
**Requires Manual Review:** ${metrics.logic.requiresManualReview ? 'YES' : 'No'}

### Detected Logic Indicators
${metrics.logic.detectedHooks.length > 0 
  ? metrics.logic.detectedHooks.map((hook: string) => `- ${hook}`).join('\n')
  : '- No complex plugins detected.'}

## 4. SEO & URL Architecture
**Permalink Structure:** \`${metrics.seo.permalinkStructure}\`
**Standard Structure:** ${metrics.seo.isStandard ? 'Yes' : 'NO (Redirects Required)'}
**Estimated Redirects:** ~${metrics.seo.redirectEstimate} URLs

### SEO Tools Detected
- **Yoast SEO:** ${metrics.seo.hasYoast ? 'Yes (Exportable)' : 'No'}
- **RankMath:** ${metrics.seo.hasRankMath ? 'Yes (Exportable)' : 'No'}

## 5. BigCommerce Plugin Recommendations
| WC Plugin | BC Recommendation | Type | Notes |
| --- | --- | --- | --- |
${metrics.pluginMappings.length > 0
  ? metrics.pluginMappings.map((m: any) => `| ${m.plugin} | ${m.recommendation} | ${m.type} | ${m.notes} |`).join('\n')
  : '| None | N/A | - | No specific mappings found. |'}

## 6. Next Steps
- [ ] Review any "RED" flags for manual verification.
- [ ] Identify third-party plugins requiring BigCommerce equivalents.
- [ ] Prepare customer communication for password resets.

---
*Generated by bc-migrate v0.1.0*
`;
  }

  private getMigrationPath(category: string): string {
    switch (category) {
      case 'GREEN': return 'Automated migration highly feasible.';
      case 'YELLOW': return 'Automated migration feasible with minor adjustments.';
      case 'RED': return 'High complexity. Requires manual architectural review.';
      default: return 'Unknown';
    }
  }

  async save(baseDir: string = './reports'): Promise<{ markdown: string; json: string }> {
    if (!fs.existsSync(baseDir)) {
      fs.mkdirSync(baseDir, { recursive: true });
    }

    const filename = `assessment-${new URL(this.result.storeUrl).hostname}-${Date.now()}`;
    const mdPath = path.join(baseDir, `${filename}.md`);
    const jsonPath = path.join(baseDir, `${filename}.json`);

    const mdContent = this.generateMarkdown();
    const jsonContent = JSON.stringify(this.result, null, 2);

    fs.writeFileSync(mdPath, mdContent);
    fs.writeFileSync(jsonPath, jsonContent);

    return { markdown: mdPath, json: jsonPath };
  }
}
